rh-ecosystem-edge/eco-goinfra

- pkg/sriov/network.go
Add function which deletes all sriov networks from the operator namespace which match a specific NetworkNamespace spec.
> Add CleanAllNetworksByTargetNamespace function to sriov package

- pkg/pod/pod.go
Adds a copy method to the pod pkg which can copy files from one of the pod's containers. Has two options:
1. With tar - creates a tar archive of a path inside the container (good for copying directories if a container supports it)
2. Without tar - copies the contents of a single file
> Add copy method to pod pkg

- pkg/pod/pod.go
The initial comment seems to be copy pasted from namespace package
// Exists checks whether the given namespace exists.
Should be
//Exists checks whether the given pod exists.
> pod pkg, fixing Exists function comment

- pkg/kmm/module.go
Fixing the : `  runtime error: invalid memory address or nil pointer dereference` while using `WithDevicePlugin*` functions
> Fix for KMM's deviceplugin

- pkg/kmm/containers.go
Calling WithModprobeSpec will cause Panic given the not initialized Args/RawArgs
> KMM: Fix panic while calling WithModprobeSpec

- pkg/bmh/baremetalhost.go
rename bmh Builder to be unique
rename filename (this one includes methods related to the single object handling; at least one more file will be added - handle list of baremetalhosts)
> rename bmh builder and file name

- pkg/kmm/containers.go
Those are required in order to make sure the dependency list in the `moduleLoadingOrder` is formed correctly.
--- 
This PR hasn't been tested yet.
Also, it requires a new version of `github.com/rh-ecosystem-edge/kernel-module-management` in `go.mod`.
> kmm: adding `moduleName` and `moduleLoadingOrder` to `modprobeSpec`.

- pkg/kmm/module.go
This is needed in order to test a module edit in KMM and make sure the old kernel-module is unloaded in favor of a new kernel-module which is being loaded.
> kmm: adding an `Update` function for modules.

- pkg/networkpolicy/networkpolicy.go
fix WithPolicyType method: setting up type value directly to the Object instead of creating an empty map when policyTypes list is empty
> networkpolicy pkg: fix WithPolicyType method

- pkg/pod/pod.go
The function allows to get a pod container's full log without passing a time-frame
> pod pkg: added GetFullLog function

- pkg/kmm/containers.go
Calling WithModprobeSpec will set empty args/rawArgs, causing module loading problem.
> initialize kmm args/rawargs only when length is greater than 0

- pkg/pod/pod.go
The existing `WithLabel` method only allows to add one label to a Pod's definition. If more want to be added the old ones will be overwritten. This new method accepts a set of labels in the form of a `map` to define all the labels required at once.
Also, the `isMutationAllowed` and the `isMountAlreadyInUseInPod` methods haven been modified to return a `bool` as the name suggests. This has been used in the different `With*` methods to leave as early as possible if the right condition is not satisfied.
> pod: add new WithLabels method

- pkg/hive/clusterimageset.go
Removes resourceVersion and creationTimestamp from clusterimageset when the object is successfully deleted. Needed to re-use initial clusterimageset builder struct
> Remove clusterimageset metadata from definition when it is deleted

- pkg/rbac/clusterrole.go
The rule does not include each available field; some can stay empty. As an example:
```go
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
name: {{ cr_name }}
rules:
- apiGroups:
- ""
resources:
- nodes
- nodes/proxy
- services
- endpoints
- pods
- namespaces
verbs:
- get
- list
- watch
- nonResourceURLs:
- /metrics
- /federate
verbs:
- get
```
> clusterrole: remove rules verification for the empty fields

- pkg/deployment/deployment.go
`WithVolumes` method allows to configure volumes on the _Deployment_ object
> WithVolumes method added to Deployment

- pkg/storage/pvc.go
Methods to works with _PersistentVolumeClaim_:
* _NewPVCBuilder_ -  builds a new _PVCBuilder_ structure
* _WithPVCAccessMode_ - configures _AccessModes_ for the Volume to have
* _WithPVCapacity_ - configures minimum resources that resource should have
* _WithStorageClass_ - configures `storageClass` required by a claim
* _Create_ - creates a `PVC` resources on the cluster
> PVC builder and auxiliary methods

- pkg/kmm/module.go
While creating a ManagedClusterModule, the Module spec definition is required.
> Adding BuildModuleSpec function to kmm module

- pkg/kmm/kernelmapping.go
This fixes the error : 
```
runtime error: invalid memory address or nil pointer dereference
Full Stack Trace
```
> kmm: fixing panic while calling RegistryTLS

- .golangci.yml
- pkg/argocd/applications.go
- pkg/kmm/module.go
- pkg/lca/seedgenerator.go
- pkg/machine/machineset.go
- pkg/mco/mcplist.go
- pkg/metallb/mlbtypes/bpgpeer.go
- pkg/metallb/mlbtypes/metallb.go
- pkg/ocm/placementbinding.go
- pkg/ocm/placementrule.go
- Enabled the enforcement of comments on exported functions.
- Added basic comments on existing checks that failed linter.
> enable linter on exported functions

- pkg/lca/imagebasedupgrade.go
This commit will allow setting the pull-secret next to the seedimage to pull.
> lca: Add ability to set pull-secret for pulling images.

- pkg/deployment/deployment.go
Example use-case is for NUMA awarding scheduling where dedicated _scheduler_ is configured
> deployment pkg: added WithSchedulerName func

- pkg/lca/imagebasedupgrade.go
This commit adds the ability to disable the automated rollback in case of failure for upgrade completion phase.
> IBU: Toggle the automated rollback for upgrade completion.

- pkg/lca/imagebasedupgrade.go
This allows controlling how long to wait before
the autorollback is attempted. Default is 1800 seconds.
> IBU: Allow setting timeout for initMonitor

- pkg/lca/imagebasedupgrade.go
This commit adds the ability to disable the LCA Init Monitor, which is a post-reboot watchdog that triggers a rollback if the upgrade is not completed within the configured timeout.
> IBU: Toggle the InitMonitor for automated rollback

- pkg/pod/pod.go
`node-role.kubernetes.io/master` was [deprecated](https://kubernetes.io/blog/2022/04/07/upcoming-changes-in-kubernetes-1-24/#api-removals-deprecations-and-other-changes-for-kubernetes-1-24) back in k8s 1.24.
This adds a function `WithTolerationToControlPlane` similar to the `WithTolerationToMaster` func.  Keeps the old func around for backwards compatibility.
Similar to: 
- https://github.com/openshift-kni/cnf-features-deploy/pull/1802
- https://github.com/test-network-function/cnf-certification-test/pull/512
> Add control-plane toleration func

- .github/workflows/makefile.yml
- Makefile
Adds the path `make test` to the Makefile and to the Github workflow.
Lays the groundwork for being able to run unit tests locally and in the CI.
> Add path for running unit-tests in Makefile

- .golangci.yml
- go.mod
- go.sum
- pkg/deployment/deployment.go
- pkg/deployment/deployment_test.go
- vendor/github.com/pmezard/go-difflib/LICENSE
- vendor/github.com/pmezard/go-difflib/difflib/difflib.go
- vendor/github.com/stretchr/testify/LICENSE
- vendor/github.com/stretchr/testify/assert/assertion_compare.go
- vendor/github.com/stretchr/testify/assert/assertion_format.go
- vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
- vendor/github.com/stretchr/testify/assert/assertion_forward.go
- vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
- vendor/github.com/stretchr/testify/assert/assertion_order.go
- vendor/github.com/stretchr/testify/assert/assertions.go
- vendor/github.com/stretchr/testify/assert/doc.go
- vendor/github.com/stretchr/testify/assert/errors.go
- vendor/github.com/stretchr/testify/assert/forward_assertions.go
- vendor/github.com/stretchr/testify/assert/http_assertions.go
- vendor/modules.txt
Builds on top of #261 
Proof of concept PR for adding unit tests wrapping some of the deployment package starting with the `Pull` func.
Notable changes:
- Added func `GetTestClients` which helps build a test client for doing unit testing.
- Changed `settings.K8sClient` to use the Interface instead of the client.
- Changed `settings.NetworkingV1Client` to `settings.NetworkingV1Inteface`.
- Vendor changes come from using the fake k8s client and the additional code needed for that as well as the stretchr/testify library.
- Changes `v1` to `appsv1` similar to #239
> Add unit tests for deployment pkg Pull func

- pkg/nodes/list.go
- pkg/nodes/node.go
Building on ideas from #270 after talking with @kononovn 
Instead of copying the entire `client.Settings` struct, only keep around the `kubernetes.Interface` that you use during some of these `Node` operations.  This could also apply to all of the other k8s-related object funcs/pkgs.
This will help ease-of-use when writing unit tests that target this code as well because you don't have to worry about the other clients, just the `kubernetes.Fake` clientset.
Does not break any public functionality.
> Limit scope of 'apiClient' var in builder in 'Node' package

- .golangci.yml
- pkg/deployment/deployment.go
- pkg/deployment/deployment_test.go
Adds unit tests for the `With...` options functions in the `deployment` package.  Modifies some of the functions to better return errors via `builder.ErrorMsg`.  Uses `stretchr/testify` to assert the expected values.
> Add unit tests for deployment options pattern

- pkg/sriov-fec/const.go
- pkg/sriov-fec/nodeconfig.go
- pkg/sriov-fec/sriovfectypes/sriovfecclusterconfig_types.go
- pkg/sriov-fec/sriovfectypes/sriovfecnodeconfig_types.go
Add sriovfec pkg together with sriov-fec-operator API. This is needed since vendoring doesn't work due to older version of sigs.k8s.io/controller-runtime pkg[0] than what is used in eco-goinfra.
[0] https://github.com/smart-edge-open/sriov-fec-operator/blob/main/go.mod#L27
> Add sriovfec pkg

- pkg/pod/pod.go
Minor modification to ExecCommand method's glog to help during troubleshooting.
Logs to include namespace, pod name and container name in which command is being executed.
> pod: modified ExecCommand method's glog Infof

- pkg/lca/imagebasedupgrade.go
- pkg/lca/seedgenerator.go
This is based on assignment
https://github.com/openshift-kni/eco-goinfra/issues/299
> lca: Limiting the client for pull and newbuilder for lca

- pkg/clients/clients.go
- pkg/configmap/configmap.go
- pkg/configmap/configmap_test.go
* Adds new type for configmaps in GetTestClients.
* Switches `apiClient` in builder to an interface.
* Fixed some return values.
> Add configmap unit tests

- pkg/cgu/cgu_test.go
- pkg/clients/clients.go
- pkg/configmap/configmap_test.go
- pkg/deployment/deployment_test.go
- pkg/metallb/adresspool_test.go
- pkg/route/route_test.go
- pkg/sriov/list_test.go
- pkg/sriov/network_test.go
- pkg/sriov/networknodestate_test.go
- pkg/sriov/operatorconfig_test.go
- pkg/sriov/policy_test.go
- pkg/velero/backup_test.go
- pkg/velero/restore_test.go
Created a `TestClientParams` struct to house parameters that are needed inside of the `GetTestClients()` func.  This allows for flexibility whenever we need to add new types to our test client.
> Use client params struct

- pkg/route/route.go
- pkg/route/route_test.go
Limits the apiClients for the route pkg. Needed for https://github.com/openshift-kni/eco-goinfra/issues/294
> limit route pkg apiClient

- pkg/configmap/configmap.go
- pkg/network/network.go
- pkg/nfd/nodefeaturediscovery.go
- pkg/proxy/proxy.go
- pkg/sriov/operatorconfig.go
- pkg/storage/pvc.go
I'm surprised the linter didn't catch these already.
> Fix extraneous fmt.Sprintf calls

- pkg/assisted/agent.go
- pkg/assisted/agentclusterinstall.go
- pkg/assisted/agentserviceconfig.go
- pkg/assisted/infraenv.go
- pkg/assisted/nmstateconfig.go
Limits apiClient for resources within the assisted pkg. Needed for https://github.com/openshift-kni/eco-goinfra/issues/295
> limit assisted pkg apiClient

- pkg/deployment/deployment.go
Follow up to: #314 
- Adds back in the `glog` calls for a few functions.
- Adjust the returned error in `validate`.
> Adjust deployment pkg returns and logs

- pkg/clients/clients.go
- pkg/ocm/policy.go
- pkg/ocm/policy_test.go
Added `NewPolicyBuilder` as well as some methods to add `PolicyTemplates` and set the `RemediationAction`. Tests for the new methods are included.
> ocm: added new policy builder and unit tests

- pkg/clients/clients.go
- pkg/ocm/policyset.go
- pkg/ocm/policyset_test.go
Added `NewPolicySetBuilder` as well as a method to add a new `Policy` to the set. Tests for the new methods are included.
> ocm: added new policy set builder and unit tests

- .github/workflows/makefile.yml
https://github.com/actions/setup-go/releases/tag/v5.0.0
If #240 was merged, this would be handled by dependabot automatically.
> Update setup-go action to v5

- .github/workflows/makefile.yml
https://github.com/actions/checkout/releases/tag/v4.1.4
If #240 was merged, this would be handled by dependabot automatically.
> Update checkout action to v4

- pkg/clients/clients.go
- pkg/ingress/ingress_test.go
- pkg/ingress/ingresscontroller.go
- pkg/ingress/ingresscontroller_test.go
Note: It looks like the `Update()` is fundamentally broken because it does not appear you can modify IngressController objects once they are created.  I tried various things to try and get it to work.
I left my test in there but commented out until we decide what to do with the `Update()` function itself.
Other changes:
* Modified the `Delete()` function to set the object to nil and return to match other package(s) functionality.
Resolves: https://github.com/openshift-kni/eco-goinfra/issues/361
> Add ingress controller unit tests

- pkg/cgu/cgu.go
- pkg/cgu/cgu_test.go
This fixes an issue where force updates could create the cgu before it was deleted, resulting in it just being deleted.
> cgu: added delete and wait to force update

- pkg/cgu/cgu.go
In #402 I accidentally used an update instead of a get inside the WaitUntilDeleted function that results in an error if the cgu is still present after the first check. This is the same situation that led to an error before albeit for a different reason.
> cgu: fix bug in wait until deleted function

- pkg/bmh/baremetalhost_test.go
In `baremetalhost_test.go` the `TestBareMetalHostWaitUntilDeleted` unit test waits only 1 second for deletion, which causes tests to fail sometimes since the actual WaitUntilDeleted function polls every 1 second and does not immediately execute. This fix just increases the wait time in the test to 2 seconds which should always be sufficient.
> bmh: fixed occasional failed unit test

- pkg/bmh/baremetalhost_test.go
Same issue as in #420, the `DeleteAndWaitUntilDeleted` test will occasionally fail. Didn't notice this function needed to be changed during that PR.
> bmh: fix test for delete and wait

- pkg/assisted/agentclusterinstall.go
- pkg/assisted/agentclusterinstall_test.go
- pkg/assisted/testdata/aci_events.json
- pkg/clients/clients.go
Adds unit tests for the agentclusterinstall resource in the assisted pkg
Needed for https://github.com/openshift-kni/eco-goinfra/issues/295
> Add unit tests for agentclusterinstall

- pkg/statefulset/list.go
- pkg/statefulset/statefulset_test.go
Allows to list _StatefulSet_ resources in all the namespaces.
> ListInAllNamespaces method added for statefulset pkg

- pkg/bmc/bmc.go
- pkg/bmc/bmc_test.go
- usage/bmc/bmc.go
bmc.SystemPowerState() returns the PowerState (string) field from the bmc's configured ComputerSystem.
> BMC: added method to get system's power state.

- pkg/kmm/containers_test.go
```
$ go tool cover -func=c.out
github.com/openshift-kni/eco-goinfra/pkg/kmm/containers.go:27:                  NewModLoaderContainerBuilder            100.0%
github.com/openshift-kni/eco-goinfra/pkg/kmm/containers.go:49:                  WithModprobeSpec                        93.8%
github.com/openshift-kni/eco-goinfra/pkg/kmm/containers.go:85:                  WithKernelMapping                       88.9%
github.com/openshift-kni/eco-goinfra/pkg/kmm/containers.go:108:                 WithImagePullPolicy                     87.5%
github.com/openshift-kni/eco-goinfra/pkg/kmm/containers.go:128:                 WithVersion                             87.5%
github.com/openshift-kni/eco-goinfra/pkg/kmm/containers.go:147:                 WithOptions                             0.0% …
```
> Some KMM related unit-tests

- .github/workflows/eco-gotests-integration.yml
Upon new PRs, clone both repos down (eco-gotests and eco-goinfra) and then replace the eco-goinfra with the local copy in the eco-gotests go.mod.  Once the replacement is done, run the `make vet` path in the eco-gotests folder to see if everything compiles correctly.
This was previously not possible to test because `eco-gotests` was private.
> Add eco-gotests 'make vet' to PR checks

- .github/workflows/eco-gotests-integration.yml
- .github/workflows/makefile.yml
Related to: https://github.com/test-network-function/cnf-certification-test/pull/2134
https://groups.google.com/g/golang-announce/c/XbxouI9gY7k
> Update Go to v1.22.4

- Makefile
`make coverage-html` generates a coverage output website.  `*.out` is already covered in the gitignore.
> Add 'make coverage-html' make path

- pkg/cgu/cgu.go
- pkg/cgu/cgu_test.go
- pkg/cgu/precachingconfig_test.go
These two files were missing tests for their versions of `Validate()`.
> Add Validate tests for pkg/cgu

- pkg/storage/pv.go
- pkg/storage/pv_test.go
This PR adds Delete, DeleteAndWait, and WaitUntilDeleted methods to the storage PVBuilder struct. Unit tests for the file, including for these new methods, have been added.
> storage: add deletes and unit tests to pv

- pkg/clients/clients.go
- pkg/storage/storageclass.go
- pkg/storage/storageclass_test.go
Added a PullClass function to the storage package; added Delete, DeleteAndWait, and WaitUntilDeleted methods to ClassBuilder; and added unit tests for all of the functions in `storageclass.go`.
> storage: add pull and deletes plus tests to storageclass

- pkg/cgu/cgu.go
- pkg/cgu/cgu_test.go
In TALM and ZTP test cases there are many scenarios where we are waiting for a CGU to be in some condition. WaitForCondition generalizes these cases (and the existing WaitUntilComplete) into a single function. Unit tests have been added for WaitForCondition as well as the existing WaitUntilComplete.
> cgu: add wait for condition and unit tests

- pkg/argocd/applications.go
When using force updates on an Argo CD application that has already been pulled from the cluster, there is a risk that the ResourceVersion is newer on the server but is also set in the Definition, resulting in the delete succeeding but not the creation during a force update.
> argocd: reset application resource version on update

- pkg/cgu/cgu_test.go
- pkg/ocm/policy_test.go
- pkg/storage/pv_test.go
There were a few older Delete, DeleteAndWait, and WaitUntilDeleted unit tests that didn't have the same coverage as the newer ones. This PR updates those tests to be more similar to newer tests with better coverage.
> update delete (and wait) unit tests for a few packages

- .github/workflows/eco-gotests-integration.yml
- .github/workflows/makefile.yml
https://groups.google.com/g/golang-announce/c/gyb7aM1C9H4
Related to: https://github.com/test-network-function/cnf-certification-test/pull/2229
> Update Go to v1.22.5

- pkg/bmc/bmc.go
- pkg/bmc/bmc_test.go
- pkg/bmc/testdata/redfish_v1_system.json
- pkg/bmc/testdata/redfish_v1_system_boot_option_Boot0000.json
- pkg/bmc/testdata/redfish_v1_system_boot_option_Boot0003.json
- pkg/bmc/testdata/redfish_v1_system_boot_options.json
- SystemBootOptions: helper function that reads the current available boot options and creates a map so the user can see the display name of each of boot option reference.
- SystemBootOrderReferences: returns a slice with the current boot order references.
- SetSystemBootOrderReferences: updates the system's boot order references. Needs a system reset so changes take effect.
> BMC: added redfish api to get and change system's boot order.

- README.md
[Rendered](https://github.com/klaskosk/eco-goinfra/blob/sync-readme/README.md#sync-tool-and-operator-types)
> readme: added instructions for sync

- pkg/ocm/kac.go
- pkg/ocm/kac_test.go
- pkg/ocm/managedcluster_test.go
Closes #544 by adding unit tests for the list and validate functions in the OCM package and modifying a few existing test cases to improve coverage a bit. This PR also resets the resourceversion during force updates to preemptively address situations like in #483.
> ocm: increased coverage for kac and mcl 

- pkg/bmc/bmc_test.go
Depending on how the timing works out, the BMC error message may be due to a context deadline exceeded or an i/o timeout. The latter is not accounted for in the test case and may cause errors during the test incoming changes action, like in [this test run].
This PR addresses it by asserting that either of these errors happened. Since both are due to timeouts, it does not change the expected behavior of the test.
[this test run]: https://github.com/klaskosk/eco-goinfra/actions/runs/10186752240/job/28179274304
> bmc: fix test failure in action

- pkg/clients/clients.go
- pkg/ocm/policyset.go
- pkg/ocm/policyset_test.go
- pkg/ocm/policysetlist.go
- pkg/ocm/policysetlist_test.go
This PR adds unit tests for list and validate for the policy set resource in the OCM package.
> ocm: added unit tests and increased policy set coverage

- pkg/pod/pod.go
- pkg/pod/pod_test.go
Refactoring functions previously defined in eco-gotests RAN subfolder:
IsPodHealthy https://github.com/openshift-kni/eco-gotests/blob/4b0fbe0b32ad910f8f4421337cfe84c4f92cefc1/tests/cnf/ran/internal/ranhelper/ranhelper.go#L14 . New function name is: WaitUntilHealthy
> pod:add WaitUntilInStatuses,WaitUntilHealthy funcs

- pkg/pod/list.go
- pkg/pod/list_test.go
Refactoring functions previously defined in eco-gotests RAN subfolder:
WaitForAllPodsInNamespacesHealthy https://github.com/openshift-kni/eco-gotests/blob/050a4e5ee720e9a776a90791c8354ac9c5aaf43e/tests/cnf/ran/talm/internal/helper/cluster.go#L146. New function name is: WaitForAllPodsInNamespacesHealthy
> pod: add WaitForAllPodsInNamespacesHealthy

- pkg/cgu/cgu.go
Similar to #483, when the CGU has ResourceVersion set on the definition, it can cause the create to fail. This results in the CGU being deleted but not created by the force update.
This situation can be achieved by calling WaitForCondition on a CGU before a force update while the CGU gets updated on the cluster in between. Has appeared in the TALM tests.
> cgu: reset resource version in force update

- pkg/clients/clients.go
- pkg/mco/kubeletconfig_test.go
- pkg/mco/machineconfig.go
- pkg/mco/machineconfig_test.go
- pkg/mco/machineconfiglist.go
- pkg/mco/machineconfiglist_test.go
* Switches the MachineConfig resource to use the runtime client and adds unit tests for the file.
* Removes the MCO client from the test clients. Note that it is still in clients.Settings until MCP is converted to runtime client.
* Renames a variable in the KubeletConfig tests that had been copied from the ocm package.
> mco: tests and runtime client for machine config

- pkg/mco/mco_test.go
- pkg/mco/mcp.go
- pkg/mco/mcp_test.go
This switches the MCP resource to the runtime client and adds unit tests for most of the methods on the builder.
For brevity, the unit tests for the list functions and the wait*** methods will come in #632.
> mco: unit tests and runtime client for mcp

- pkg/clients/clients.go
- pkg/mco/mcp_test.go
- pkg/mco/mcplist.go
- pkg/mco/mcplist_test.go
Added unit tests and switched to the runtime client for the MCP list functions. Also adds unit tests to the remaining untested MCP functions. Now that the package is complete, removes the machineconfig client from clients.
> mco: unit tests and runtime client for mcp list 

- .golangci.yml
- scripts/golangci-lint.sh
- Fixed a number of deprecated linters in the configuration.
- Disabled the `printf` linter under `govet`.
- Disabled "SA1006" from staticcheck.
https://github.com/golangci/golangci-lint/releases/tag/v1.60.3
Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2372
> Update GolangCI-lint to v1.60.3

- pkg/deployment/deployment.go
- pkg/deployment/deployment_test.go
To match the `daemonset` line of the same operation.  The `daemonset` package doesn't require the containerSpec to be a pointer so we can remove it here to prevent `nil` dereferencing.
> deployment: remove pointer from containerSpec

- pkg/nodes/list.go
- pkg/nodes/list_test.go
- pkg/nodes/node_test.go
- pkg/nodes/nodes_test.go
This PR adds tests for the nodes/list file as well as some test helpers. Additionally, nodes_test.go has been renamed to node_test.go to match the corresponding node.go.
> nodes: add list unit tests

- pkg/pod/list_test.go
- pkg/pod/pod.go
- pkg/pod/pod_test.go
This PR adds unit tests to the basic pod functions (NewBuilder, Pull, Create, Delete, Get, Exists) and refactors the existing tests in the package to be more in line with those from other packages.
> pod: add basic unit tests

- pkg/bmh/hfs.go
- pkg/bmh/hfs_test.go
Adds the HostFirmwareSettings resource to the bmh package and unit tests for the functions it exports.
> bmh: add HostFirmwareSettings resource and unit tests

- pkg/nodes/node.go
- pkg/nodes/node_test.go
Added unit tests to all of the node functions except the ones that involve draining and the drain helper.
> nodes: add unit tests for all but drain

- pkg/daemonset/daemonset.go
- pkg/replicaset/replicaset.go
- pkg/service/service.go
Adds `GetGVR()` functions to the `daemonset` and `replicaset` packages.
`GetServiceGVR()` exists in the `service` package but is inconsistent with the calls to other `GetGVR()` functions so I made a duplicated.  Once this merges I can go change the references to `GetServiceGVR()` in the eco-gotests repo and then we can remove this here.
> daemonset,replicaset,service: added getGVR func

- pkg/clients/clients.go
The `Namespace` object needs to be added to the client objects list for writing unit tests.
> Add Namespace to k8sClientObjects

- pkg/bmc/bmc.go
Similar to: https://github.com/openshift-kni/eco-goinfra/pull/329
There are now 572 references to TODO() and 0 references to Background() outside of "schemes".
> context consistency: switch Background() to TODO()

- pkg/metallb/bgppeer.go
- pkg/metallb/bgppeer_test.go
Adding metallb connect timer. Connect timer is part of mlbtypesv1beta2
> metallbv2-add-connect-timer

- pkg/networkpolicy/list.go
- pkg/networkpolicy/list_test.go
Changes:
- Added `List()` func and corresponding unit test.
> networkpolicy: add List() func

- pkg/networkpolicy/networkpolicy.go
Similar to: #667 
Adds a `GetGVR()` function to the networkpolicy package.
> networkPolicy: Add GetGVR()

- pkg/daemonset/daemonset.go
- pkg/deployment/deployment.go
- pkg/icsp/icsp.go
- pkg/machine/machineset.go
- pkg/mco/machineconfig.go
- pkg/namespace/namespace.go
- pkg/ocm/managedcluster.go
- pkg/rbac/clusterrole.go
- pkg/rbac/clusterrolebinding.go
- pkg/rbac/role.go
- pkg/rbac/rolebinding.go
- pkg/replicaset/replicaset.go
- pkg/secret/secret.go
- pkg/service/service.go
- pkg/sriov/poolconfig.go
- pkg/storage/storageclass.go
Be consistent in the `Delete()` funcs in that they should be using the `builder.Definition` instead of the `builder.Object` structs when referencing variables.  It's a mix right now and I feel that the `Definition` should be where we are gathering that information.
> Ensure Delete() funcs use Definition

- pkg/deployment/deployment.go
In #672 it was mentioned that we are missing a `glog` entry for when a deployment does not exist.
> deployment: add glog to Delete() exists

- pkg/bmh/baremetalhost.go
- pkg/bmh/baremetalhost_test.go
Similar to other Delete() functions, we do not return errors when an object already doesn't exist.
Builds from changes in: #379
> baremetalhost: Delete() should return nil if not exists

- pkg/assisted/infraenv.go
Built from: #379 
Adds a `glog` entry and returns nil instead of an error for Delete() that does not exist.
Similar to: #690
> assisted/infraenv: add glog and return nil to Delete()

- pkg/rbac/clusterrole.go
- pkg/rbac/clusterrole_test.go
- pkg/rbac/clusterrolebinding.go
- pkg/rbac/role.go
- pkg/rbac/role_test.go
- pkg/rbac/rolebinding.go
Similar to: https://github.com/openshift-kni/eco-goinfra/pull/387
Just changing `v1` to `rbacv1` to better match the rest of the repo.
> rbac: v1 to rbacv1 import consistency

- pkg/serviceaccount/serviceaccount.go
- pkg/serviceaccount/serviceaccount_test.go
Changes:
- `apiClient` becomes an interface.
- Adjust returns in Create().
- Add unit tests to cover the whole file.
> serviceaccount: add unit tests and improvements

- pkg/resourcequotas/resourcequotas.go
I forgot to add a `GetGVR()` function in my resource quotas PR #701
> resourcequotas: add GetGVR() func

- .github/workflows/eco-gotests-integration.yml
- .github/workflows/makefile.yml
- .github/workflows/sync-libs.yaml
- .golangci.yml
- README.md
- go.mod
Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2402
Don't worry about merging this until after the next release if needed.
> Update Go to v1.23.2

- pkg/velero/backup.go
- pkg/velero/backupstoragelocation.go
- pkg/velero/backupstoragelocation_test.go
- pkg/velero/restore.go
> velero: adjust delete() returns

- pkg/clusterlogging/clusterlogforwarder.go
- pkg/clusterlogging/clusterlogforwarder_test.go
The validate method of the clusterLogForwarderBuilder currently does not check for the errorMsg of the builder being set. This PR adds a check for the errorMsg and update the corresponding tests.
Following up on #727.
> clusterlogging: add errorMsg check to validate

- pkg/clusterversion/clusterversion.go
- pkg/clusterversion/clusterversion_test.go
* Added unit tests to the clusterversion package
* Switched the clusterversion package to use the runtime client
* Switched to use constants from configv1 instead of string literals
> clusterversion: add unit tests and runtime client

- pkg/network/network.go
- pkg/network/network_test.go
* Add unit tests for network.go in the network package.
* Switch network.go to use the runtime client and add the Get method.
> network: add unit tests and switch to go client

- pkg/ibgu/ibgu.go
* Update all logs to include the namespace of the IBGU since it is a namespaced resource
* Adds an additional log statement for when the Get function fails
Without the additional log when Get fails, it is impossible to tell if the Exist function is returning true because the object truly does not exist or if it returns true because the get failed for a reason other than not found.
An example of this is if the apiClient does not have the CRD for the ibgu, Exist can return true even though that is clearly not the case, causing weird behaviors elsewhere. This PR at least makes the true error more visible in logs.
> ibgu: add additional log in Get and namespaces to logs

- pkg/daemonset/daemonset.go
- pkg/replicaset/replicaset.go
Seems to be an extraneous `fmt.Errorf` on these two packages `daemonset` and `replicaset`.
> fmt: fix error return(s)

- .github/workflows/makefile.yml
Changes the `makefile.yml` workflow to have two separate jobs: `lint` and `test`.
The `lint` job can take minutes on its own and is an easy way to speed up the PR checking process by passing off the `test` portion to another runner.
> ci: Split out linting from testing

- pkg/hive/clusterdeployment.go
- pkg/hive/clusterdeployment_test.go
- Add generic constructor so we can support clusterdeployment platforms other than agentBareMetal
> Add generic clusterdeployment constructor to support more platforms

- pkg/ocm/placementbinding.go
- pkg/ocm/placementrule.go
- pkg/ocm/policy.go
- pkg/ocm/policyset.go
Similar to a change from #763, Exist can return true even if Get returns an error, causing Pull to succeed but Definition to be nil. By adding a log to Get, this error is no longer silent and has a more obvious root cause.
> ocm: add logs to get errors

- pkg/metallb/bgppeer.go
- pkg/metallb/bgppeer_test.go
Adding to to bgppeer the option of using dynamicASN to configure the remote asn.
> metallb: add bgppeer dynamicASN type

- pkg/network/operator.go
- pkg/network/operator_test.go
Depends-on: openshift-kni/eco-goinfra#765
* Added unit tests to operator.go in the network package, except for the Set* functions since they are effectively untestable in our current setup.
* Made sure scheme was being added in the Pull function
* A few naming edits
> network: operator unit tests

- pkg/pod/list.go
- pkg/pod/pod.go
The WaitForAllPodsInNamespacesHealthy function replaces functions in eco-gotests but behaves slightly differently, causing CI instability for cnf/ran.
Previously, the pods were listed every loop then all were checked to see if they were healthy. This means pods that get deleted during the waiting were ignored. Now, however, they cause a failure.
This PR addresses the issue by skipping pods that no longer exist during the waiting period. After all, a pod that does not exist cannot be unhealthy.
> pod: change wait for pods healthy behavior

- pkg/bmc/bmc.go
- pkg/bmc/bmc_test.go
Previously we only delete the ssh session.Close(), the SSH client was still connected after deletion. Instead, use ssh client.Close() to fully disconnect the SSH connection.
> Use SSH Client.Close() to close SSH connection 

- pkg/namespace/namespace.go
* Adjust the Delete returns as in #379
* Add an extra log to DeleteAndWait for other errors that may occur getting the namespace. (Similar problem to Exists() returns)
> namespace: adjust delete returns and extra log

- pkg/bmh/baremetalhost.go
- pkg/bmh/hfs.go
> bmh: address return consistency

- pkg/clusterlogging/clusterlogforwarder.go
- pkg/clusterlogging/clusterlogging.go
- pkg/clusterlogging/elasticsearch.go
- pkg/clusterlogging/lokistack.go
> clusterlogging: adjust return consistency

- pkg/deployment/deployment.go
No actual returns added here, mostly just changing the references to the pointer.  I find it more consistent to declare variables as a pointer initially then to return a pointer to an object at the end of a function.
> deployment: adjust return consistency

- pkg/machine/machineset.go
> machine: adjust return consistency

- pkg/metallb/addresspool.go
- pkg/metallb/bfdprofile.go
- pkg/metallb/bgpadvertisement.go
- pkg/metallb/bgppeer.go
- pkg/metallb/metallb.go
> metallb: adjust return consistency

- pkg/nmstate/nmstate.go
- pkg/nmstate/policy.go
Follow up to: https://github.com/openshift-kni/eco-goinfra/pull/848
Apparently I missed the `Validate()` func when updating the returns.  I also updated the `Create()` to match the example scheme from @klaskosk.
> nmstate: update create() and returns

- pkg/nto/performanceprofile.go
Follow up to: https://github.com/openshift-kni/eco-goinfra/pull/851
The `performanceprofile` file was missed from #355.
> performanceprofile: adjust return consistency

- pkg/servicemesh/controlplane.go
- pkg/servicemesh/memberroll.go
> servicemesh: adjust return consistency

- pkg/pod/container.go
- pkg/pod/container_test.go
- pkg/pod/pod.go
> pod: adjust return consistency

- pkg/sriov/network.go
- pkg/sriov/networknodestate.go
- pkg/sriov/operatorconfig.go
- pkg/sriov/policy.go
- pkg/sriov/poolconfig.go
> sriov: adjust return consistency

- pkg/replicaset/replicaset.go
Adjusts the delete function to also set the Object to nil when the replicaset does not exist. Similar to #379.
> replicaset: adjust delete return

- pkg/namespace/namespace.go
- Changes namespace pkg back to using corev1 client for Create method
> namespace: use corev1 client to create namespaces

- pkg/nfd/nodefeaturediscovery.go
- pkg/nfd/nodefeaturediscovery_test.go
Broken out from #355 
I had to re-arrange the NewBuilder func to properly handle errors which then forced an adjustment of the unit test cases.
> nfd: adjust return consistency

- pkg/networkpolicy/multinetegressrule.go
- pkg/networkpolicy/multinetegressrule_test.go
- pkg/networkpolicy/multinetingressrule.go
- pkg/networkpolicy/multinetingressrule_test.go
- pkg/networkpolicy/multinetworkpolicy.go
> networkpolicy: adjust return consistency

- pkg/rbac/clusterrole.go
- pkg/rbac/clusterrole_test.go
- pkg/rbac/clusterrolebinding.go
- pkg/rbac/role.go
- pkg/rbac/role_test.go
- pkg/rbac/rolebinding.go
> rbac: adjust return consistency

- pkg/metallb/bgppeer_test.go
Follow up to #881 that fixes the unit test failure. It seems like the unit tests ran when the PR base was main, which has this change, then got merged into release-4.17 without it, causing the failure.
> metallb: fix bgppeer test after syncing types

- pkg/velero/restore.go
- pkg/velero/restore_test.go
* Added unit tests for the Restore Get, Exists, Create, Update, and Delete methods.
* Updated returns to be more in line with #355.
* Added coverage to NewRestoreBuilder and PullRestore functions for when the apiClient is nil.
> velero: add more restore unit test coverage

- pkg/webhook/validatingwebhook.go
- pkg/webhook/validatingwebhook_test.go
> webhook: add validating webhook unit tests

- pkg/namespace/namespace.go
`CleanObjects` uses graceperiod=0 which is not recommended to have smooth deletion of resources. Hence, removing `GracePeriodSeconds` parameter.
> namespace: Update CleanObjects

- pkg/bmc/bmc_test.go
The timeout error message in TestBMCSerialConsole takes two different forms. Tests on the main branch already account for this but release-4.16 does not have the fix. This PR replaces the test on release-4.16 with the one from main.
> bmc: backport serial console test fix

- pkg/oran/clustertemplate.go
- pkg/oran/clustertemplate_test.go
- pkg/oran/clustertemplatelist.go
- pkg/oran/clustertemplatelist_test.go
This PR adds the ClusterTemplate resource and its unit tests to the oran package. Like with the NodePool and Node resources, this is meant to be read only and therefore has only the Pull, Get, and Exists methods.
> oran: added ClusterTemplate resource and unit tests

- pkg/oran/node.go
- pkg/oran/node_test.go
- pkg/oran/nodelist.go
- pkg/oran/nodelist_test.go
Depends-on: #901 
This PR adds the Node resource and its unit tests to the oran package. Like with the NodePool resource, this PR only implements the read only methods since the operator should handle the actual modifications.
> oran: add Node resource and unit tests 

- pkg/pod/pod.go
[PR](https://github.com/openshift-kni/eco-goinfra/pull/891) ensures grace-period is not set to while terminating pod. But kubernetes uses GracePeriod defined in Pod Spec. However, `TerminationGracePeriodSeconds` in PodSpec is being set to 0 for all new pods defined with `NewBuilder` unless explicitly updated with `WithTerminationGracePeriodSeconds`
Hence, removing grace-period=0 in default pod definition.
> pod: remove default GracePeriod

- pkg/bmc/bmc.go
- pkg/bmc/bmc_test.go
When performing a reset action (power on, power off, reset, etc.), it is useful to verify the action actually took place. WaitForSystemPowerState allows one to poll the BMC until the desired power state occurs, similar to functions already used in cnf/ran in eco-gotests.
> bmc: add WaitForSystemPowerState function

- pkg/oran/provisioningrequest.go
- pkg/oran/provisioningrequest_test.go
This PR adds a number of additional methods (along with unit tests) to the ProvisioningRequest resource:
* WithTemplateParameter(s) and GetTemplateParameters make it easier to work with the TemplateParameters field.
* DeleteAndWait since ProvisioningRequest deletion includes deprovisioning and may take a while.
* WaitForCondition for awaiting changes to the status conditions.
> oran: add extra methods to ProvisioningRequest

- pkg/namespace/namespace.go
CleanObjects is not working when there is only 1 pod/resource in terminating state
> namespace: edit CleanObjects

- pkg/namespace/namespace.go
CleanObjects is not working when there is only 1 pod/resource in terminating state
> namespace: edit CleanObjects [4.16]

- pkg/namespace/namespace.go
CleanObjects is not working when there is only 1 pod/resource in terminating state
> namespace: edit CleanObjects [4.14]

- pkg/assisted/agentclusterinstall.go
- pkg/assisted/agentclusterinstall_test.go
- pkg/kmm/containers_test.go
- pkg/networkpolicy/multinetegressrule_test.go
- pkg/networkpolicy/multinetingressrule_test.go
- pkg/nmstate/policy_test.go
- pkg/oadp/dataprotectionapplication_test.go
- pkg/olm/operatorgroup_test.go
Makes sure that imports are using a more descriptive name than `v1`.
Note: This does not touch the `schemes` folder that are copies of other code.
Similar to:
- #239 
- #387 
- #694 
- #711
> Import consistency

- pkg/certificate/signingrequest.go
- pkg/certificate/signingrequest_test.go
- pkg/certificate/signingrequestlist.go
- pkg/certificate/signingrequestlist_test.go
* Adds the CertificateSigningRequest resource and creates a new certificate package for it.
* Adds listing functions, along with a method to wait until all CSRs are approved.
* Unit tests are provided for all exported functions.
> certificate: add new package for CSR resource

- pkg/siteconfig/clusterinstance.go
- pkg/siteconfig/clusterinstance_test.go
When provisioning clusters using oran, the ClusterInstance is managed by the oran-o2ims operator. It is useful to wait for changes to the ExtraLabels field to be propogated to the ClusterInstance by the operator, something the WaitForExtraLabel method allows.
> siteconfig: add WaitForExtraLabel method to CIBuilder

- pkg/pod/list.go
- pkg/pod/list_test.go
- pkg/pod/pod.go
- pkg/pod/pod_test.go
This is part 1 of a 3 part effort to replace pod.WaitForAllPodsInNamespacesHealthy.
1. (This PR) Add new helpers to eco-goinfra that simplify waiting for pods healthy and list on every iteration.
2. Change the cluster.WaitForRecover function to use the new eco-goinfra helpers. Also a small change in cnf/ran/talm.
3. Remove the old helpers from eco-goinfra.
Motivation:
The old WaitForRecover function would list the pods each iteration, ensuring that pods started after calling the function will be checked as well as ignoring pods that later end up deleted. A workaround for the latter of these issues was merged in #808.
Additionally, the current pod.WaitForAllPodsInNamespacesHealthy has too many parameters and is hard to test properly. The current unit tests for it do not adequately cover …
> pod: add new health functions

- .github/workflows/eco-gotests-integration.yml
- .github/workflows/makefile.yml
- .github/workflows/sync-libs.yaml
Rather than manually having to run CI, this PR updates the sync-libs workflow to call the CI workflows and label the sync PR accordingly.
[Example action run](https://github.com/klaskosk/eco-goinfra/actions/runs/13295025927)
[Example PR](https://github.com/klaskosk/eco-goinfra/pull/11)
> infra: call CI from sync-libs workflow

- integration/deployment_test.go
Adjust the deployment test to preemptively delete the test namespace prior to running the test to prevent any weirdness when running `make integration-test` locally.
> integration: adjust deployment test

- integration/common.go
- integration/deployment_test.go
Adds an `integration/common.go` with two funcs:
- CreateTestContainerDefinition()
- PreEmptiveNamespaceDeleteAndSetup()
Stuff that is "shared" between our various integration tests can be placed here to add more code re-use.
> integration: add common funcs

- integration/common.go
- integration/configmap_test.go
- integration/deployment_test.go
- Add tests for `configmap` package.
- I also had to modify the `deployment` package to better handle running in parallel.  I made a separate PR to adjust it [here](https://github.com/openshift-kni/eco-goinfra/pull/951).
Related to: https://github.com/openshift-kni/eco-goinfra/pull/714
> integration: add configmap test

- integration/daemonset_test.go
- pkg/daemonset/daemonset.go
- Added Create and Delete integration tests for the `daemonset` resource.
- I had to modify the `IsDaemonsetReady` to actually match what we do in the `certsuite-qe` repo [here](https://github.com/redhat-best-practices-for-k8s/certsuite-qe/blob/main/tests/globalhelper/daemonset.go#L60-L66).  For some reason, when testing, the `status` wouldn't have conditions listed and it would never come back as ready.  When this merges, I'll change our QE to use the eco-goinfra logic.
- I also added `!k8serrors.IsNotFound(err)` to the daemonset `Delete()` to better handle already "missing" daemonsets.
Related to: 
- #714
> integration: add daemonset tests

- .github/workflows/sync-libs.yaml
Resolves: https://github.com/openshift-kni/eco-goinfra/issues/959
If any more `cron` related jobs (eg. #942) get added, they will also need the conditional statement.
> ci: prevent forks from running nightly crons

- .github/workflows/eco-gotests-integration.yml
- .github/workflows/integration-testing-nightly.yml
- .github/workflows/integration-testing.yml
- .github/workflows/makefile.yml
- .github/workflows/sync-libs.yaml
Adds a nightly YAML for triggering both k8s and OCP runs nightly (not tied to any PR).
This runs the exact `make integration-test` path, but against OCP in a nightly fashion.
Brings in changes from:
- #937 
- #961
> PoC: Add nightly OCP integration test

- pkg/imageregistry/imageregistry.go
Related to the ongoing issues with Pull and Exists.
> imageregistry: log failed Get

- pkg/olm/clusterserviceversion.go
- pkg/olm/clusterserviceversion_test.go
For the ORAN tests it is necessary to be able to update a CSV. This PR adds the Update() method to the olm package and the corresponding unit test.
> olm: added Update() method and unit test

- pkg/ocm/managedcluster.go
- pkg/ocm/managedcluster_test.go
Added the function DeleteAndWait() for managedcluster and the corresponding unit test.
> ocm: added delete and wait function

- go.mod
- vendor/modules.txt
Using the `replace` directive causes trouble in dependant projects that need to generate installable binaries [1].
Also, there is no point in depending on an invalid version:
```
$ go get github.com/openshift/api@v3.9.1-0.20191111211345-a27ff30ebf09+incompatible
go: github.com/openshift/api@v3.9.1-0.20191111211345-a27ff30ebf09+incompatible: invalid pseudo-version: preceding tag (v3.9.0) not found
```
[1] https://github.com/golang/go/issues/44840
Please, note that this PR does not bring any real dependency changes, as `vendor/` directory go files are not affected.
> deps: Remove `openshift/api` replace directive

- pkg/bmc/bmc.go
- pkg/bmc/bmc_test.go
- pkg/bmc/testdata/redfish_v1_system_virtual_media.json
- pkg/bmc/testdata/redfish_v1_system_virtual_media_1.json
- pkg/bmc/testdata/redfish_v1_system_virtual_media_2.json
This PR adds a function to the bmc package to boot from CD only once. This functionality is required for the ORAN system tests based on the IBI-based provisioning.
> bmc: added bootfromcd function

- pkg/service/service.go
Follow up to:
#667 
Depended on:
https://github.com/openshift-kni/eco-gotests/pull/209
https://github.com/openshift-kni/eco-gotests/pull/502
> service: remove deprecated GetServiceGVR() func

- internal/sync/configs/ocs-config.yaml
- pkg/schemes/ocs/nadutils/net-attach-def.go
Go 1.24 changes the way vet works and this causes our CI to break with the ocs nadutils schemes. This PR uses the replace_imports feature of the sync to correct the single line where this error occurs without affecting functionality.
> sync: fix ocs sync for go 1.24

- .github/workflows/sync-libs.yaml
By default, GitHub actions will apply a `success()` condition to the if unless there is another status check function used. Since the label function is meant to run even if previous steps failed, we need to use a status check function to replace the default success condition. This PR adds a `!cancelled()` condition to address that and prevent issues where the job runs even if dependencies have been cancelled.
> sync: update label job if condition

- pkg/clients/clients.go
- pkg/imageregistry/imageregistry.go
- pkg/imageregistry/imageregistry_test.go
Although the imageregistry package has been updated to use the controller-runtime client already, it still uses the switch statement in the clients package to add objects rather than AttachScheme like other packages. This PR updates the package and removes the case from the clients package.
> imageregistry: update to use scheme attachers

- .github/workflows/integration-testing-nightly.yml
- .github/workflows/integration-testing.yml
Changes:
- Better name the integration jobs.
- Add `nick-fields/retry` to the `make integration-test` calls to enable retries.
> integration: add retries

- pkg/lca/seedgenerator.go
- pkg/lca/seedgenerator_test.go
The WaitUntilComplete() function was not behaving correctly. It was not pollling until the deadline because the return of the fmt.Errorf("seedgenerator did not complete") was making the loop to stop. This PR changes the returned error when the condition is not met and updates the unit test accordingly.
> lca: changed returned error in seedgenerator waituntilcomplete

- .github/workflows/eco-gotests-integration.yml
- .github/workflows/integration-testing.yml
- .github/workflows/makefile.yml
- .github/workflows/sync-libs.yaml
Although sync-libs uses the sync branch for its changes, all of the subsequent tests would run on the default branch. This hides the errors from the tests unless main also has broken CI.
This PR updates all the workflows that sync-libs calls to take a branch input that determines what to checkout. Other triggers for the workflows just use the GITHUB_SHA for that event type.
[Example action run](https://github.com/klaskosk/eco-goinfra/actions/runs/14064759649/job/39384364965)
> ci: fix sync-libs testing

- pkg/kmm/module.go
- pkg/kmm/module_test.go
Adding support for tolerations in KMM Modules.
The checks are only added for `key`, `effect` and `operator` fields.
For `value` and `seconds` , given that are optional, no checks were added.
> kmm: add support for tolerations

- pkg/nmstate/policy.go
- pkg/nmstate/policy_test.go
Add a ethernet interface with IP addresses to the nmstate policy
> cnf network: add ethernet interface type to nmstate policy

- integration/namespace_test.go
Adds a new integration test specifically for the `namespace` package.
Changes:
* Added `TestNamespaceCreate` to verify the creation of a namespace and its existence in the cluster.
* Added `TestNamespaceDelete` to verify the deletion of a namespace and ensure it no longer exists in the cluster.
* Added `TestNamespaceCleanObjects` to verify the cleaning of objects (e.g., pods) within a namespace.
> integration: Add namespace pkg test

- .github/workflows/eco-gotests-integration.yml
- .github/workflows/integration-testing.yml
- .github/workflows/makefile.yml
Workflows that are called by a scheduled workflow inherit the schedule event type so the check for workflow_call was always false. It is also unnecessary since the inputs will be null if not applicable so the `||` is enough to provide a fallback.
> ci: fix actions not using passed branch

- pkg/nmstate/policy.go
- pkg/nmstate/policy_test.go
Add to nmstate policy the ability to enable an ethernet interface allowing only ipv6 link-local address.
> nmstate: policy add ethernet interface with ipv6 linklocal address

- pkg/argocd/applications.go
- pkg/argocd/applications_test.go
As part of an effort to decouple and make reusable the gitdetails helper from cnf/ran in eco-gotests, this PR adds more generic versions of these helpers as methods on the Application builder itself.
WithGitPathAppended is a more specific version of WithGitDetails that is more aligned with the common use case of updating to use a subdirectory of the git repo. WithGitDetails may still be used to update all of the git details if necessary.
DoesGitPathExist can be called similar to WithGitPathAppended and checks if that path would exist. The way it checks should be mostly portable between git hosts, at least enough to cover the common cases.
WaitForSourceUpdate allows verifying a change to the Application's source has taken effect.
> argocd: add git functions to application

- pkg/amdgpu/deviceconfig.go
- pkg/amdgpu/deviceconfig_test.go
Added package & tests for the AMD GPU Operator DeviceConfig
> AMD GPU Operator; Adds DeviceConfig PKG & Tests

- integration/pod_test.go
* Added Create and Delete integration tests for the pod resource.
* Added an ExecCommand test too for the pod resource. Since we do not have any unit tests for this function (and #602 to add them is a draft), it will be good to have some assurance it is working.
The latter point is also motivated by a desire to use a FallbackExecutor to enable the websocket executor for Kubernetes 1.30+ (OpenShift 4.17+). This will be a future PR, however.
> integration: add pod tests

- pkg/kmm/preflightvalidation.go
- pkg/kmm/preflightvalidation_test.go
The new `release-2.4`  of [KMM](https://github.com/rh-ecosystem-edge/kernel-module-management/tree/release-2.4/api/v1beta2) will drop the `preflightvalidationocp` crd. 
The tests will be moved to the u/s crd: `preflightvalidation`
This PR is a precursor of the crd removal and assures that there are no breakages.
> hw-accel: prepare remove of preflightvalidationocp crd

- pkg/kmm/module.go
ModuleLoaderSpec is now optional. Creating it when it is needed.
> kmm: handle nils while using ModuleLoaderSpec

- pkg/deployment/deployment.go
- pkg/deployment/deployment_test.go
WithTerminationGracePeriodSeconds method defines gracePeriod of test pods created by the deployment. This supports graceful termination of pods when the default 30secs is not enough.
> deployment: add WithTerminationGracePeriodSeconds method

- pkg/statefulset/statefulset.go
- pkg/statefulset/statefulset_test.go
Method _WithPodAnnotations_ allows to configure _annotations_ on the pod(s) managed by the _StatefulSet_
Assisted-by: Cursor
> WithPodAnnotations method for StatefulSet added

- pkg/pod/pod.go
This PR attempts to address the cause behind the integration test flakiness by not redirecting stdin in ExecCommand.
Assisted-by: Cursor
> pod: attempt to address integration test flakiness
