pkg/assisted/infraenv.go
pkg/bmh/bmh.go
pkg/hive/clusterdeployment.go
pkg/kmm/module.go
pkg/mco/mcp.go
pkg/metallb/addresspool.go
pkg/metallb/bfdprofile.go
pkg/metallb/bgpadvertisement.go
pkg/metallb/bgppeer.go
pkg/nad/builder.go
pkg/rbac/clusterrole.go
pkg/rbac/clusterrolebinding.go
pkg/rbac/role.go
pkg/rbac/rolebinding.go
pkg/service/service.go
pkg/serviceaccount/serviceaccount.go
pkg/sriov/network.go
pkg/sriov/policy.go
pkg/statefulset/statefulset.go

Adds pull functions for all pkgs

Add pull functions for all pkgs

---

CODEOWNERS

Include CODEOWNERS file for automatically selecting reviewers on future PRs

Add CODEOWNERS to repository

---

pkg/pod/list.go

Added WaitForAllPodsInNamespaceRunning()

Add WaitForAllPodsInNamespaceRunning()

---

pkg/mco/machineconfig.go
pkg/mco/mc.go

Adding support for MachineConfig that allows support for changing configuration of a node.
Added suport for 
- WithKernelArguments
- WithExtensions
- WithFips
- WithKernelType

Adding MachineConfig package

---

pkg/argocd/applications.go
pkg/argocd/argocd.go

Added argocd pkg

---

pkg/kmm/containers.go
pkg/kmm/kernelmapping.go

Adding the rest of the helpers related to KMM 1.1 release.

kmm: adding WithVersion and WithInTreeModuleToRemove

---

pkg/argocd/applications.go

Added WithGitDetails mutation function, this is needed in order to define the argocd app with git details.

Add mutation function to applications.go

---

pkg/deployment/deployment.go

Adding WithServiceAccountName function to deployment pkg.

Adding WithServiceAccountName function to deployment pkg

---

pkg/statefulset/list.go
pkg/statefulset/statefulset.go

Refactors the statefulset list functionality
Closes https://github.com/openshift-kni/eco-goinfra/issues/122

Refactor statefulset pkg list function

---

pkg/olm/clusterserviceversion.go
pkg/olm/clusterserviceversionlist.go
pkg/olm/packagemanifest.go
pkg/olm/packagemanifestlist.go

Refactors the olm list functions
Closes https://github.com/openshift-kni/eco-goinfra/issues/120

Refactor olm pkg list functions

---

pkg/hive/clusterdeployment.go
pkg/hive/clusterdeploymentlist.go

Refactors the hive list functionality
Closes https://github.com/openshift-kni/eco-goinfra/issues/114

Refactor hive pkg list function

---

pkg/scc/scc.go

new methods added to the scc package:
- WithHostDirVolumePlugin
- WithFSGroupRange
- WithHostIPC
- WithHostNetwork
- WithHostPID
- WithHostPorts
- WithReadOnlyRootFilesystem
- WithDefaultAddCapabilities
- WithPriority
- WithGroups
- WithVolumes

extended scc handler

---

pkg/assisted/agentclusterinstall.go

Cleans up and simplifies the way conditions are checked in the agentclusterinstall resource.
Previously condition handling was overly complicated and not aligned with any other packages of the repository.

Cleanup agentclusterinstall condition handling

---

pkg/assisted/agent.go
pkg/assisted/agentclusterinstall.go
pkg/assisted/agentserviceconfig.go
pkg/assisted/infraenv.go
pkg/hive/clusterdeployment.go
pkg/hive/clusterimageset.go

Added an assignment to builder.Object in the infraenv, agentclusterinstall, agent and agentserviceconfig files. Added a Delete and Wait function for the infraenv.

assisted pkg: changes to Update functions

---

pkg/assisted/agentclusterinstall.go

Fixes a flaky error with agentclusterinstall condition checking. Currently if attempting to read conditions immediately after creating the agentclusterinstall, no conditions are returned because they haven't been published yet

Add wait to agentclusterinstall for condition publishing

---

pkg/bmh/baremetalhost.go
pkg/bmh/list.go

baremetalhost.go: 
- Pull method was replaced with Discover
- new method added GetBmhPowerOnStatus
baremetalhosts.go:
-  created new buider to handle bmh lists
- WaitToBeAllInGoodOperationalStatusFor method added

bmh pkg: list handeling method was added

---

pkg/assisted/agentclusterinstall.go

Adds a GetEvents method for AgentClusterInstall. Will be used for determining state of installed/installing clusters

Add GetEvents method for AgentClusterInstall

---

pkg/olm/clusterserviceversion.go
pkg/olm/clusterserviceversionlist.go

IsSucceeded, GetPhase and ListAllInNamespaceWithNamePattern methods added to the olm pkg, csv handler

olm pkg, csv handler: new methods were added

---

pkg/infrastructure/infrastructure.go

infrastructure pkg added

---

pkg/clusterlogging/clusterlogforwarder.go

clusterloggingforwarding package added to the clusterlogging

clusterloggingforwarding package added to the clusterlogging

---

pkg/ingress/ingresscontroller.go

ingresscontroller pkg added

---

pkg/clusterlogging/clusterlogforwarder.go

- NewClusterLogForwarderBuilder
- WithOutput
- WithPipeline

new methods added to the clusterlogging/clusterlogforwarder

---

pkg/bmh/list.go
pkg/clusteroperator/list.go
pkg/deployment/list.go
pkg/hive/clusterdeploymentlist.go
pkg/machine/machinesetlist.go
pkg/mco/mcplist.go
pkg/namespace/list.go
pkg/nmstate/policylist.go
pkg/nodes/list.go
pkg/nto/performanceprofilelist.go
pkg/olm/clusterserviceversionlist.go
pkg/olm/installplanlist.go
pkg/olm/packagemanifestlist.go
pkg/pod/list.go
pkg/sriov/networklist.go
pkg/sriov/networknodestatelist.go
pkg/sriov/policylist.go
pkg/statefulset/list.go

Refactoring List functions  to take an optional ListOptions argument

Refactoring List functions in several packages

---

pkg/pod/list.go

list.go:
- ListByNamePattern
- WaitForSpecificPodReplicasCountInNamespace

new methods were added to the pod pkg

---

pkg/pod/container.go

Besides adding _SecurityCapability_ there're use cases to specify _Dropped_ capabilities.

WithDropSecurityCapabilities method added

---

pkg/pod/pod.go

Method that allows to configure _ConfigMap_ volume on the pod

WithVolume method added to pod pkg

---

pkg/pod/container.go

Method that allows to configure volume mounts within container.

Added WithVolumeMounts method

---

pkg/deployment/deployment.go

Method that allows to set toleration on the _Deployment_

Method WithToleration added to deployment pkg

---

pkg/kmm/preflightvalidationocp.go

This PR adds the PreflightValidationOCP support pkg to eco-goinfra

Add preflightvalidationocp to kmm pkg

---

pkg/clients/clients.go
pkg/storage/storageclass.go

Adds the StorageClassBuilder struct to the storage pkg

Add StorageClassBuilder to storage pkg

---

pkg/storage/pvc.go

Methods to delete _PersistentVolumeClaim_ resources from the cluster

Delete method for PersistentVolumeClaim

---

pkg/storage/pvc.go

Added method that defines what type of volume is required by the claim.

Method to set PVC VolumeMode

---

pkg/lca/imagebasedupgrade.go

This should hep distinct among the CRs

lifecycleagent package: renaming functions names for imagebasedupgrade.

---

pkg/lca/imagebasedupgrade.go

This aims at helping with bckup/restore automation.

lca: Adding oadpConent to ImageBasedUpgrade.

---

pkg/deployment/list.go

Method to list deployments in all the namespaces

ListInAllNamespaces method for Deployments added

---

pkg/lca/imagebasedupgrade.go

Adding the option to add extraManifests to the IBU. This in turn allows to create/configure resources
during upgrade.

ibu: extraManifests support

---

pkg/pod/network.go

Add staticAnnotation func with name only to pod > network.go

pod pkg: added bond annotation func network.go

---

pkg/lca/imagebasedupgrade.go

This will allow providing a configmap reference with additional images.

lca - ibu: additionionalImages option is added.

---

pkg/pod/network.go

Add function to create annotations for multiple interfaces with dual stack IP addresses.

pod pkg: added multi net dual stack annotation func network.go

---

pkg/secret/secret.go

Secret pkg seems that it misses the Update func. 
- Adding it with this PR . 
- Update WithData glog comment

secret pkg: added Update func plus minor comment change

---

pkg/network/operator.go

Backport of https://github.com/openshift-kni/eco-goinfra/pull/228

network operator: increased timer

---

README.md
pkg/clusterlogging/clusterlogging.go
pkg/deployment/deployment.go
pkg/metallb/metallb.go
pkg/namespace/namespace.go
pkg/nmstate/nodenetworkstate.go
pkg/servicemesh/member-roll.go

Found some typos while digging through the repo.

Found typos across various files

---

go.mod
go.sum
pkg/nmstate/policy.go
pkg/sriov/networknodestate.go
pkg/sriov/policy.go
pkg/webhook/mutatingwebhook.go
pkg/webhook/validatingwebhook.go
vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/helper.go
vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/sriovnetworknodepolicy_types.go
vendor/github.com/k8snetworkplumbingwg/sriov-network-operator/api/v1/sriovnetworknodestate_types.go
vendor/modules.txt

backport: added webhook pkg, updated sriov and nmstate pkgs

backport: added webhook pkg, updated sriov and nmstate pkgs

---

pkg/lca/imagebasedupgrade.go

Adds a check to the ibu Update method that waits for reconciliation to finish before setting builder fields

Wait for IBU to finish reconciling after update

---

pkg/deployment/deployment.go
pkg/pod/pod.go

Similar to: https://github.com/openshift-kni/eco-gotests/pull/624
I accidentally broke this with #239.

pod,deployment pkg: fixed network annotation

---

pkg/daemonset/daemonset.go

Added functions to update the daemonset builder with Hostnetwork and configmap volume mount.

daemonset: added WithHostNetwork and WithVolume functions

---

pkg/clients/clients.go
pkg/velero/backup.go
pkg/velero/backup_test.go
pkg/velero/restore.go
pkg/velero/restore_test.go

Add the restore resource to the velero pkg

Add restore struct to velero pkg

---

pkg/deployment/deployment.go
pkg/deployment/deployment_test.go
pkg/deployment/list.go

Resolves: #270 
- Adds unit tests for the deployment package.  
- Modifies the interface used in the `Builder`.

Add deployment unit tests

---

pkg/clusteroperator/clusteroperator.go

clusteroperator: added Pull function

add new method to the co pkg: Pull function

---

pkg/lca/imagebasedupgrade.go

No support for multiple IBU CRs

IBU can only be named upgrade

---

pkg/clients/clients.go
pkg/events/events.go
pkg/events/events_test.go
pkg/events/list.go

Add event units tests

---

pkg/clusteroperator/clusteroperator.go

clusteroperator pkg: GetConditionReason method added

clusteroperator pkg: GetConditionReason method added

---

pkg/apiservers/kubeapiserver.go
pkg/apiservers/openshiftapiserver.go

new apiservers pkg added:
- openshiftapiserver
- kubeapiserver

new apiservers pkg added (openshiftapiserver&kubeapiserver included)

---

README.md

We now require ading unit test for every package.
Adding a respective note to the readme.

Adding a note re unit test.

---

pkg/sriov/network.go
pkg/sriov/network_test.go

Adds the ability to supply a vlan protocol.

sriov pkg: add vlanproto with func

---

pkg/apiservers/kubeapiserver.go
pkg/apiservers/openshiftapiserver.go

fixing PollUntilContextTimeout methods for the apiservers pkg

fixing PollUntilContextTimeout methods for the apiservers pkg

---

pkg/clusteroperator/clusteroperator.go

clusteroperator pkg: add validation verification before operator status check

clusteroperator pkg: add validation verification to methods

---

pkg/clients/clients.go
pkg/ocm/placementrule.go
pkg/ocm/placementrule_test.go

Added `NewPlacementRuleBuilder`  and a unit test for it.

ocm: added new placement rule builder and unit tests

---

pkg/clients/clients.go
pkg/imageregistry/imageregistry.go

created new "imageregistry' pkg and its scheme added to the client.go + new, used by imageregistry, method was added to the pods

imageregistry pkg added

---

pkg/clients/clients.go
pkg/nodesconfig/const.go
pkg/nodesconfig/nodesconfig.go
pkg/nodesconfig/nodesconfig_test.go

nodesConfig pkg added (nodes.config object)

---

pkg/pod/container.go
pkg/pod/pod_test.go

Method _WithCustomResourcesRequests_ allows to request custom resources for a container for e.g. _SR-IOV_ resource.

WithCustomResourcesRequests method added

---

pkg/nodesconfig/nodesconfig.go

nodesconfig.pkg: typo correction

nodesconfig.pkg: typo correction

---

pkg/nodes/list.go

WaitForAllNodesToReboot method enhancements

nodes.pkg: WaitForAllNodesToReboot method enhancements

---

pkg/lca/ibu_test.go
pkg/lca/imagebasedupgrade.go

AdditionalImages was removed from the CRD.

ibu: remove AdditionalImages from IBU pkg

---

pkg/clients/clients.go
pkg/imageregistry/const.go
pkg/imageregistry/imageregistry.go
pkg/imageregistry/imageregistry_test.go

WithStorage and Get Storage methods added + unit test

imageregistry pkg: WithStorage and Get Storage methods added + unit test

---

pkg/clients/clients.go
pkg/clusteroperator/clusteroperator.go
pkg/clusteroperator/clusteroperator_test.go
pkg/clusteroperator/const.go
pkg/clusteroperator/list.go

switch to the goclient.Client, Get method added + unit test

clusteroperator pkg: switch to the goclient.Client, Get method added + unit test

---

pkg/networkpolicy/multinetegressrule.go
pkg/networkpolicy/multinetegressrule_test.go

Related to other similar `networkpolicy` pkg unit test PRs:
- #376 
- #350

Add multinetegress unit tests

---

pkg/namespace/list.go
pkg/networkpolicy/multinetegressrule_test.go
pkg/nodes/list.go
pkg/olm/installplanlist.go
pkg/pod/list.go
pkg/sriov/networknodestate.go

Import consistency

---

pkg/networkpolicy/multinetegressrule_test.go
pkg/networkpolicy/multinetingressrule.go
pkg/networkpolicy/multinetingressrule_test.go

Related to other similar `networkpolicy` pkg unit test PRs:
- #376 
- #350 
- #382

Add multinetingress unit tests

---

pkg/msg/msg.go
pkg/msg/msg_test.go

Resolves: https://github.com/openshift-kni/eco-goinfra/issues/392

Add unit tests for msg package

---

pkg/clients/clients.go
pkg/console/consoleoperator.go
pkg/console/consoleoperator_test.go

new consoleoperator object handeling added to the console pkg + unit test

new consoleoperator object handeling added to the console pkg + unit test

---

pkg/nodes/list.go

Remove the err message inside the wait method.

nodes list: WaitForAllNodesToReboot fix

---

pkg/lca/seedgenerator.go

The seedgenerator can have a specific name only.
Updating respectively.

lca: updating the seedgenerator - singleton

---

scripts/golangci-lint.sh

Related to: https://github.com/test-network-function/cnf-certification-test/pull/2054

Update GolangCI-lint to v1.58.1

---

pkg/clients/clients.go
pkg/clusterlogging/clusterlogforwarder.go
pkg/clusterlogging/clusterlogforwarder_test.go

clusterlogforwarder adjustments + unit test added

clusterlogforwarder adjustments + unit test added

---

pkg/servicemesh/controlplane.go
pkg/servicemesh/controlplane_test.go

servicemesh controlplane adjustments + unit test added

servicemesh controlplane adjustments + unit test added

---

pkg/sriov/list_test.go
pkg/sriov/poolconfiglist.go

Design was changed: there is no default sriovpoolconfig.

sriov pkg: Renamed CleanAllPoolConfigs func

---

pkg/bmc/bmc.go
pkg/bmc/bmc_test.go
pkg/bmc/testdata/redfish_v1_chassis.json
pkg/bmc/testdata/redfish_v1_chassis_nopower.json
pkg/bmc/testdata/redfish_v1_chassiscollection.json
pkg/bmc/testdata/redfish_v1_power.json

Might be worth waiting till #419 is merged before merging this PR.

bmc: add power on/off and power usage

---

pkg/lca/seedgenerator.go

Adding a check to the WithSeedImage function for non-empty seedimage.

lca: adding a check for seedimage name

---

pkg/bmc/bmc.go
pkg/bmc/bmc_test.go

Refactored the Power Cycle system reset to perform a PowerOff + On reset actions as a fallback mechanism when PowerCycle reset type is not supported by the system.
Also fixes in some traces.

BMC: PowerCycle alternate implementation

---

pkg/clients/clients.go
pkg/velero/backupstoragelocation.go
pkg/velero/backupstoragelocation_test.go
pkg/velero/backupstoragelocationlist.go

Add backupstoragelocation struct to velero pkg

add backupstoragelocation to velero pkg

---

pkg/apiservers/kubeapiserver_test.go

Bumps this file's coverage to 85.7%.

Add TestKubeAPIServerBuilderValidate func

---

pkg/clients/clients.go
pkg/daemonset/daemonset.go
pkg/daemonset/daemonset_test.go

Resolves: #464 
Builds upon changes in #355 and #379 as well.

Add daemonset pkg unit tests

---

pkg/sriov/operatorconfig.go
pkg/sriov/operatorconfig_test.go

WithConfigDaemonNodeSelector method added

sriov pkg: WithConfigDaemonNodeSelector method added

---

pkg/clients/clients.go
pkg/keda/scaleobject.go
pkg/keda/scaleobject_test.go
pkg/nodes/node.go

ScaleObject object handler added to the keda pkg

keda pkg: ScaleObject object handler added

---

pkg/service/service.go
pkg/service/service_test.go

methods added:
-  Update
- WithLabels
- WithSelector

service pkg, new methods added: Update, WithLabel, WithSelector

---

pkg/clients/clients.go
pkg/oadp/const.go
pkg/oadp/dataprotectionapplication.go
pkg/oadp/dataprotectionapplication_test.go
pkg/oadp/dataprotectionapplicationlist.go
pkg/oadp/oadptypes/dataprotectionapplication.go

Add the oadp pkg and stuct for interacting with the dataprotectionapplication resource

Add OADP pkg and dataprotectionapplication

---

.golangci.yml
pkg/clusterversion/clusterversion.go
pkg/clusterversion/const.go

Adding infra functions to support OCP upgrade

clusterversion: Added With,Wait functions

---

pkg/nto/performanceprofile.go
pkg/nto/performanceprofile_test.go

WithAdditionalKernelArgs method added

ntp pkg: WithAdditionalKernelArgs method added

---

pkg/nad/masterplugin.go
pkg/nad/nadtypes.go
pkg/pod/network.go
pkg/sriov/network.go

This is a backport for sriov eco-gotest allmulti test cases.  Those test require changes in the pod, sriov, and nad network pkgs.

backport for pod, sriov and nad pkgs

---

pkg/storage/ocs.go
pkg/storage/ocs_test.go

storage pkg: ocs adjustments

---

pkg/clusterlogging/lokistack.go
pkg/clusterlogging/lokistack_test.go

new methods added to the lokistack:
- WithLimits
- WithTemplate

clusterlogging pkg: new methods added to the lokistack

---

pkg/clusterlogging/clusterlogging.go
pkg/clusterlogging/clusterlogging_test.go

clusterlogging handler adjustments + new methods:
- WithCollection
- WithManagementState
- WithLogStore
- WithVisualization

clusterlogging pkg: clusterlogging handler adjustments + new methods

---

pkg/clients/clients.go
pkg/secret/secret_test.go

Unittests for the secret package.

secret: added package unit tests

---

pkg/clusteroperator/clusteroperator.go
pkg/clusteroperator/clusteroperator_test.go
pkg/clusteroperator/list.go
pkg/clusteroperator/list_test.go

Added function to verify all the clusteroperators version after the ocp upgrade

Added VerifyClusterOperatorsVersion func

---

pkg/storage/list.go
pkg/storage/list_test.go

list PV&PVC method added + unit test

storage.pkg: List PV&PVC methods added + unit test

---

pkg/storage/pv.go
pkg/storage/pv_test.go

storage pkg: PV handler adjustments

---

pkg/clients/clients.go
pkg/lso/iso_test.go
pkg/lso/localvolumediscovery.go
pkg/lso/localvolumediscovery_test.go

lso pkg: localvolumediscovery enhancements + unit test + WithNodeSelector method added

localvolumediscovery enhancements, unit test, WithNodeSelector added

---

pkg/clients/clients.go
pkg/lso/localvolumediscovery.go
pkg/lso/localvolumediscovery_test.go
pkg/lso/localvolumeset.go
pkg/lso/localvolumeset_test.go

localvolumeset enhancements, unit test, new methods added:
- WithNodeSelector
- WithStorageClassName
- WithVolumeMode
- WithFSType
- WithMaxDeviceCount
- WithDeviceInclusionSpec
-

lso pkg: localvolumeset enhancements, unit test, new methods added

---

internal/sync/sync.go

Adds excludes fields for sync configs. Allows us to remove files and directories from projects we clone into our repository. Useful for cases where we want to remove unneeded files or remove go.mod and vendored files in favor of our own cloned files.

sync: add excludes field for repo

---

pkg/clients/clients.go

- Modifies Settings struct to contain trackable/modifiable scheme field
- Enables us to move scheme initialization from clients pkg to each resources' respective pkg
- Allows the client to be more lightweight and only aware of resource schemes upon accessing a resources' NewBuilder or Pull functions

Add modifiable scheme to client settings struct

---

internal/sync/sync.go

The recursion in excludeFiles abandons searching at the current level in favor of searching a subdirectory when one is found. For example, if there is a directory `dir`, with subdirectories `a` and `b` which have `a_test.go` and `b_test.go`, respectively, the current implementation will walk `dir`, then `a`, remove `a_test.go`, and return. This would skip checking `b`, however, and has been changed to use filepath.WalkDir and just ignore the root directory to avoid that scenario.
Additionally, refactor has been updated to use filepath.WalkDir since it did not need the extra information from filepath.Walk that makes filepath.Walk less efficient.

sync: fix excludes for nested dirs

---

internal/sync/sync.go

Previously, the sync process would attempt to reverse the changes to be applied to the local directory and diff it against the cloned directory. If they were the same, the local directory would be reverted using git. If they were different, the cloned directory would have the opposite changes applied and then be copied to the local directory.
This relied on the local directory already being in git and would cause errors when it was not tracked in git. This PR changes this process to apply the desired updates to the cloned directory, diff it against the local, and overwrite the local if there is a difference. This does not rely on git to revert the changes and should halve the number of changes to files.

sync: refactor sync process

---

internal/sync/configs/hive-config.yaml

sync: enable auto sync for hive

---

.github/workflows/sync-libs.yaml

Reverts openshift-kni/eco-goinfra#566

Revert "ci: sync job, remove token from env variables"

---

pkg/clients/clients.go
pkg/ocm/ocm_test.go
pkg/ocm/policy.go
pkg/ocm/policy_test.go
pkg/ocm/policylist.go
pkg/ocm/policylist_test.go

This PR adds unit tests for list and validate for the policy resource in the OCM package.

ocm: added unit tests and increased policy coverage

---

pkg/clients/clients.go
pkg/ocm/placementbinding.go
pkg/ocm/placementbindingList.go
pkg/ocm/placementbinding_test.go
pkg/ocm/placementbindinglist_test.go

This PR adds unit tests for list and validate for the placement binding resource in the OCM package.

ocm: increased placement binding coverage

---

pkg/clients/clients.go

Gives user's the ability to customize their test builder within test cases when more advanced configuration is needed

clients: update test client to support modifying test builder

---

pkg/cgu/cgu.go
pkg/cgu/cgu_test.go

This PR adds a few methods to allow waiting on the batch remediation progress for individual clusters on the CGU. Unit tests for these new methods are included.

cgu: added WaitUntilClusterInState and unit tests

---

pkg/ocm/policy.go
pkg/ocm/policy_test.go

WaitForMessageToContain waits until the latest message on the policy contains the expected message. Unit tests have also been added.

ocm: added wait for status message to contain to policy 

---

pkg/ocm/kac.go
pkg/ocm/kac_test.go

Added the WaitUntilSearchCollectorEnabled method to wait for the search collector to be enabled. The Get method has been added for the kac resource as well. Unit tests for both are included.

ocm: added wait until search collector enabled to kac

---

pkg/imageregistry/imageregistry.go
pkg/imageregistry/imageregistry_test.go

Like in the cgu package, this PR adds waiting for a condition to the imageregistry package. Unit tests for the function are included.

imageregistry: add wait for condition

---

.github/workflows/eco-gotests-integration.yml
.github/workflows/makefile.yml
.github/workflows/sync-libs.yaml

Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2360

Update Go to v1.22.6

---

pkg/sriov/network.go

Changes to accommodate multiple capabilities.

sriov: update WithCapabilities method

---

CODEOWNERS

Updated the CODEOWNERS to add me now that I'm a maintainer.

owners: add klaskosk to code owners file

---

pkg/deployment/deployment.go

Adjust deployment pkg return consistency

---

pkg/ibgu/ibgu.go
pkg/ibgu/ibgu_test.go

Add ibgu package for ImageBasedGroupUpgrades custom resource.
Depends-On: https://github.com/openshift-kni/eco-goinfra/pull/663

Add ibgu package

---

pkg/ibgu/ibgu.go
pkg/ibgu/ibgu_test.go

Pull and DeleteAndWait are required for functional tests.

IBGU: Added PullIBGU, DeleteAndWait, and WaitUntilDeleted methods to ibgu package

---

pkg/metallb/const.go
pkg/metallb/frr.go
pkg/metallb/frr_test.go
pkg/metallb/metallb.go
pkg/metallb/metallb_test.go

The PR adds a FRRconfiguration pkg.

metallb: add FrrConfigurationBuilde and unit tests

---

pkg/service/list.go
pkg/service/list_test.go
pkg/service/service.go
pkg/service/service_test.go

Changes:
- Adds List() func and corresponding unit tests.
- Changed `apiClient` in the builder to `CoreV1Interface`.
- Address `return` values on certain functions, brought in from #379.

service: add List() func; various improvements

---

pkg/statefulset/statefulset.go
pkg/statefulset/statefulset_test.go

Adds the functionality and the unit test for a Delete() func in the statefulset package.

statefulset: add Delete() func

---

pkg/deployment/deployment.go
pkg/deployment/deployment_test.go

Similar to other `WaitUntilDeleted` funcs in other packages.

deployment: add WaitUntilDeleted func and test

---

pkg/siteconfig/clusterinstance.go
pkg/siteconfig/clusterinstance_test.go

Add siteconfig package for ClusterInstance custom resource.
Please help to review this PR when you have a time. Thanks !
/Peri M
to: @mcornea , @klaskosk , @trewest
cc: @yliu127

siteconfig: Add siteconfig package for ClusterInstance custom resource

---

pkg/storage/pvc.go

For my reviewers, I'm pretty sure the "Group" is just blank correct?  I can't seem to find anything that tells me different?

pvc: add GetGVR() func

---

pkg/metallb/frrnodestate.go
pkg/metallb/frrnodestate_test.go
pkg/metallb/frrnodestatelist.go
pkg/metallb/frrnodestatelist_test.go

Add cnf metallb frrnodestate funcs

metallb frr: add frrNodeState

---

pkg/resourcequotas/list.go
pkg/resourcequotas/list_test.go
pkg/resourcequotas/resourcequotas.go
pkg/resourcequotas/resourcequotas_test.go

Adds a `resourcequotas` package to eco-goinfra.

resourcequotas: add pkg and unit tests

---

pkg/clusterversion/clusterversion.go
pkg/console/console.go
pkg/infrastructure/infrastructure.go
pkg/network/network.go
pkg/proxy/proxy.go

Similar to:
- #239 
- #387 
- #694

import consistency: configv1

---

pkg/clients/clients.go
pkg/poddisruptionbudget/poddisruptionbudget.go
pkg/poddisruptionbudget/poddisruptionbudget_test.go
pkg/resourcequotas/resourcequotas.go

Adds `poddisruptionbudget` as a package in eco-goinfra.

pdb: add poddisruptionbudget pkg

---

pkg/siteconfig/clusterinstance.go
pkg/siteconfig/clusterinstance_test.go

Addding 'NewClusterInstanceBuilder, Update, WaitFor...Condition' methods in siteconfig package.
@klaskosk , @trewest , Please help to review this PR when you get a time. Thanks!

siteconfig: Add 'NewBuilder, Update, WaitForCondition...' and other methods

---

pkg/nad/builder.go

nad: adjust delete returns()

---

pkg/metallb/addresspool.go
pkg/metallb/bfdprofile.go
pkg/metallb/bgpadvertisement.go
pkg/metallb/bgppeer.go
pkg/metallb/l2advertisement.go
pkg/metallb/metallb.go

metallb: adjust delete() returns

---

pkg/machine/machineset.go

machineset: adjust delete() returns

---

pkg/kmm/module.go

kmm module: adjust delete() returns

---

pkg/kmm/managedclustermodule.go

managedclustermodule: adjust delete() returns

---

pkg/clusterlogging/clusterlogging.go
pkg/clusterlogging/clusterlogging_test.go

clusterlogging: adjust delete() returns

---

pkg/clusterlogging/clusterlogforwarder.go
pkg/clusterlogging/clusterlogforwarder_test.go

clusterlogforwarder: adjust delete() returns

---

pkg/cgu/cgu.go
pkg/cgu/cgu_test.go

cgu: adjust delete() returns

---

pkg/assisted/agentserviceconfig.go

agentserviceconfig: adjust delete() returns

---

pkg/assisted/agentclusterinstall.go
pkg/assisted/agentclusterinstall_test.go

agentclusterinstall: adjust delete() returns

---

pkg/icsp/icsp.go
pkg/icsp/icsp_test.go

* Added unit tests for the icsp package
* Switched ICSPBuilder to use the runtime client
* Other improvements and more logging

icsp: added unit tests and switch to runtime client

---

pkg/lca/imagebasedupgrade.go

lca imagebasedupgrade: adjust delete() returns

---

catalog-info.yaml
docs/README.md
mkdocs.yml

* Remove weird links
* Fix techdocs so they can use the existing README.md

Update QE Toolbelt catalog

---

pkg/kmm/preflightvalidationocp.go

kmm preflightvalidationocp: adjust delete() returns

---

pkg/secret/secret.go

secret: adjust delete() returns

---

pkg/webhook/mutatingwebhook.go
pkg/webhook/validatingwebhook.go

webhook: adjust delete() returns

---

pkg/scc/scc.go

scc: adjust delete() returns

---

pkg/storage/ocs.go
pkg/storage/ocs_test.go
pkg/storage/pvc.go
pkg/storage/storageclass.go

storage: adjust delete() returns

---

pkg/route/route.go

route: adjust delete() returns

---

pkg/olm/catalogsource.go
pkg/olm/clusterserviceversion.go
pkg/olm/installplan.go
pkg/olm/operatorgroup.go
pkg/olm/packagemanifest.go
pkg/olm/subscription.go
pkg/rbac/clusterrole.go
pkg/rbac/clusterrolebinding.go
pkg/rbac/role.go
pkg/rbac/rolebinding.go

olm: adjust delete() returns

---

pkg/nfd/nodefeaturediscovery.go

nfd: adjust delete() returns

---

pkg/ocm/placementbinding.go

ocm placementbinding: adjust delete() returns

---

pkg/ocm/policy.go
pkg/ocm/policy_test.go

ocm policy: adjust delete() returns

---

pkg/hive/clusterdeployment.go
pkg/pod/pod_test.go

clusterDeployment: adjust delete() returns

---

pkg/ocm/placementrule.go

ocm placementrule: adjust delete() returns

---

pkg/infrastructure/infrastructure.go
pkg/infrastructure/infrastructure_test.go

* Added unit tests to the infrastructure package
* Updated the infrastructure package to use the runtime client

infrastructure: unit tests and runtime client

---

pkg/servicemesh/controlplane.go
pkg/servicemesh/memberroll.go

servicemesh: adjust delete() returns

---

pkg/sriov-fec/nodeconfig.go
pkg/sriov/network.go
pkg/sriov/operatorconfig.go
pkg/sriov/policy.go
pkg/sriov/poolconfig.go

sriov: adjust delete() returns

---

pkg/ocm/managedcluster.go
pkg/ocm/managedcluster_test.go

- Add Create and WithHubAcceptsClient methods to managedcluster struct
- Add unit tests for Create and WithHubAcceptsClient

Add managedcluster Create and WithHubAcceptsClient methods

---

pkg/nad/list.go
pkg/nad/list_test.go

nad pkg: nad list option added

---

pkg/route/route.go
pkg/route/route_test.go

route pkg: WithHostDomain method added + test

route pkg: WithHostDomain method added + test

---

pkg/deployment/deployment.go
pkg/deployment/deployment_test.go

deployment pkg: WithNodeAffinity method added + test

deployment pkg: WithAffinity method added + test

---

pkg/pod/container.go
pkg/pod/container_test.go

WithReadinessProbe, WithTTY and WithStdin methods added to the container handler

pod pkg: WithReadinessProbe, WithTTY and WithStdin methods added to the container handler

---

pkg/pod/container.go
pkg/pod/container_test.go

pod pkg: WithReadinessProbe method added to the container config

pod pkg: WithReadinessProbe method added to the container config

---

pkg/velero/backup.go
pkg/velero/backup_test.go

* Added unit tests to cover Get, Exists, Create, Update, and Delete for the Backup builder.
* Updated the returns to be more in line with #355.

velero: add more backup unit tests

---

.github/workflows/eco-gotests-integration.yml
.github/workflows/makefile.yml
.github/workflows/sync-libs.yaml

Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2594

Update Go to v1.23.3

---

pkg/sriov/networknodestate.go
pkg/sriov/networknodestate_test.go
pkg/sriov/operatorconfig.go
pkg/sriov/operatorconfig_test.go

Added  :
1. WithDisablePlugins  and RemoveDisablePlugins funcs for the SriovOperatorConfig CR
2. GetTotalVFs func for the SriovNetworkNodeState CR

sriov pkg: add DisablePlugins and GetTotalVFs methods

---

pkg/ocm/policyset.go

policyset: adjust delete() returns

---

pkg/ibi/imageclusterinstall.go
pkg/ibi/imageclusterinstall_test.go

Added the ability to set ici.spec.caBundleRef field.

lca ibi: Added WithCABundle function.

---

pkg/siteconfig/clusterinstance.go
pkg/siteconfig/clusterinstance_test.go

Added the ability to set clusterinstance.spec.caBundleRef field.

lca ibi: Added WithCABundle function to siteconfig.

---

pkg/assisted/agent.go

Broken out from: https://github.com/openshift-kni/eco-goinfra/pull/379

assisted agent: adjust delete() returns

---

pkg/argocd/applications.go
pkg/argocd/argocd.go

argocd: adjust return consistency

---

pkg/assisted/agent.go
pkg/assisted/agentclusterinstall.go
pkg/assisted/agentserviceconfig.go
pkg/assisted/infraenv.go
pkg/assisted/nmstateconfig.go

assisted: adjust return consistency

---

pkg/ibgu/ibgu.go

ibgu: adjust return consistency

---

pkg/clusteroperator/clusteroperator.go

clusteroperator: adjust return consistency

---

pkg/events/events.go

events: adjust return consistency

---

pkg/hive/clusterdeployment.go
pkg/hive/clusterimageset.go
pkg/hive/config.go

hive: adjust return consistency

---

pkg/ibi/imageclusterinstall.go

ibi: adjust return consistency

---

pkg/icsp/icsp.go

icsp: adjust return consistency

---

pkg/idms/idms.go

idms: adjust return consistency

---

pkg/kmm/containers.go
pkg/kmm/kernelmapping.go
pkg/kmm/managedclustermodule.go
pkg/kmm/module.go
pkg/kmm/preflightvalidationocp.go

kmm: adjust return consistency

---

pkg/mco/kubeletconfig.go
pkg/mco/machineconfig.go
pkg/mco/mcp.go

mco: adjust return consistency

---

pkg/lca/imagebasedupgrade.go
pkg/lca/seedgenerator.go

lca: adjust return consistency

---

pkg/lso/localvolumediscovery.go
pkg/lso/localvolumeset.go

lso: adjust return consistency

---

pkg/console/console.go

console: adjust return consistency

---

pkg/metallb/addresspool.go
pkg/metallb/bfdprofile.go
pkg/metallb/bgpadvertisement.go
pkg/metallb/bgppeer.go
pkg/metallb/frr.go
pkg/metallb/frrnodestate.go
pkg/metallb/l2advertisement.go
pkg/metallb/metallb.go

metallb: adjust return consistency

---

pkg/nad/builder.go
pkg/nad/masterplugin.go

nad: adjust return consistency

---

pkg/kmm/module.go

kmm/module: adjust return consistency

---

pkg/network/operator.go

network: adjust return consistency

---

pkg/nmstate/nmstate.go
pkg/nmstate/nodenetworkstate.go
pkg/nmstate/policy.go

nmstate: adjust return consistency

---

pkg/nodes/node.go

nodes: adjust return consistency

---

pkg/namespace/namespace.go

namespace: adjust return consistency

---

pkg/nto/performanceprofile.go

nto: adjust return consistency

---

pkg/olm/catalogsource.go
pkg/olm/clusterserviceversion.go
pkg/olm/installplan.go
pkg/olm/operatorgroup.go
pkg/olm/packagemanifest.go
pkg/olm/subscription.go

olm: adjust return consistency

---

pkg/ocm/kac.go
pkg/ocm/managedcluster.go
pkg/ocm/placementbinding.go
pkg/ocm/placementrule.go
pkg/ocm/policy.go
pkg/ocm/policyset.go

ocm: adjust return consistency

---

pkg/ocm/placementbinding.go

Follow up to: #852 
These were missed from #355.

placementbinding: adjust returns

---

pkg/namespace/namespace.go

Follow up to: #844 
This was missed from #355.

namespace: returns follow-up

---

pkg/scc/scc.go

scc: adjust return consistency

---

pkg/webhook/mutatingwebhook.go

webhook: adjust return consistency

---

pkg/statefulset/statefulset.go

statefulset: adjust return consistency

---

pkg/storage/objectbucketclaim.go
pkg/storage/ocs.go
pkg/storage/pv.go
pkg/storage/pvc.go
pkg/storage/pvc_test.go

storage: adjust return consistency

---

pkg/cgu/cgu_test.go
scripts/golangci-lint.sh

Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2667

Update GolangCI to v1.63.3

---

pkg/sriov-fec/nodeconfig.go

sriov-fec: adjust return consistency

---

pkg/webhook/validatingwebhook.go

Follow up to: https://github.com/openshift-kni/eco-goinfra/pull/869
These were missed in the original PR.

validatingwebhook: adjust return consistency

---

pkg/hive/clusterimageset.go

Follow up to: #822 
These were missed as part of this PR.

hive clusterimageset: return consistency

---

.golangci.yml
scripts/golangci-lint.sh

Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2705

Update GolangCI-lint to v1.63.4

---

.github/workflows/eco-gotests-integration.yml
.github/workflows/makefile.yml
.github/workflows/sync-libs.yaml

Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2609

Update Go to v1.23.5

---

pkg/namespace/namespace.go

backport of https://github.com/openshift-kni/eco-goinfra/pull/891

namespace: backport CleanObjects update

---

pkg/pod/pod.go

backport https://github.com/openshift-kni/eco-goinfra/pull/909

pod: remove default GracePeriod

---

pkg/ocm/managedcluster.go
pkg/ocm/managedcluster_test.go

In cases where the labels on a ManagedCluster are managed by a ClusterInstance, it is useful to be able to wait for the label to propogate. This PR adds the WaitForLabel method to address this scenario.

ocm: add WaitForLabel method to ManagedClusterBuilder

---

.github/workflows/eco-gotests-integration.yml
.github/workflows/makefile.yml
.github/workflows/sync-libs.yaml
go.mod

Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2766

Update Go to v1.23.6

---

pkg/sriov/networknodestate.go
pkg/sriov/networknodestate_test.go
pkg/sriov/operatorconfig.go
pkg/sriov/operatorconfig_test.go

https://github.com/openshift-kni/eco-goinfra/pull/801

[release-4.17]sriov pkg: add DisablePlugins and GetTotalVFs methods

---

pkg/bmh/dataimage.go
pkg/bmh/dataimage_test.go

- Add dataimage resource and tests to bmh pkg

bmh: add dataimage resource

---

pkg/namespace/namespace.go
pkg/namespace/namespace_test.go

backport https://github.com/openshift-kni/eco-goinfra/pull/642

namespace: add RemoveLabels method [4.16]

---

pkg/metallb/bgppeer.go
pkg/metallb/bgppeer_test.go

backport https://github.com/openshift-kni/eco-goinfra/pull/781/files

[release-4.17] metallb: add bgppeer dynamicASN type

---

pkg/nad/masterplugin.go
pkg/nad/nadtypes.go

Add host-device network-attachment to the nad pkg.

cnf network: add nad host-device

---

scripts/golangci-lint.sh

Minor version update to match openshift-kni/eco-gotests#578

lint: update to golanci-lint v2.1.5

---

pkg/oran/provisioningrequest.go
pkg/oran/provisioningrequest_test.go

Currently, there is no way to assert that a ProvisioningRequest only becomes fulfilled after a change has been made. This is especially impactful with the use of the O2IMS API, where the information about specific policies is not returned. Without being able to check the policies to know if the ProvisioningRequest has implemented any day2 changes, it becomes necessary to know the ProvisioningRequest had not already been fulfilled at a certain time.
Conveniently, the existing WaitUntilFulfilled method has been redefined in terms of WaitForPhaseAfter by allowing zero times to turn off the check for update times.
This situation also applies to other phases than fulfilled so the method is now more general and can support all the ways to wait for the ProvisioningPhase.

oran: add WaitForPhaseAfter method 

---

Makefile

Just some minor changes to the `Makefile`.

makefile: quality-of-life

---

.github/workflows/integration-testing-nightly.yml
.github/workflows/integration-testing.yml
integration/common.go
integration/configmap_test.go
integration/daemonset_test.go
integration/deployment_test.go
integration/namespace_test.go
integration/networkpolicy_test.go

Playing around with trying to eliminate the timeouts that are randomly happening in the integration test.

experiment: eliminate integration test timeouts

---

pkg/dns/dns.go
pkg/dns/dns_test.go

dns object handler added (dnses.config.openshift.io)

dns object handler added

---

pkg/serviceaccount/serviceaccount.go

Unit tests are blocked by kubernetes/client-go#1396.

serviceaccount: add CreateToken method

---

pkg/pod/pod.go

To avoid further proliferation of methods for getting pod logs, this PR adds a new GetLogsWithOptions method that allows passing in the PodLogOptions directly. The existing two log functions have been rewritten in terms of this function.

pod: refactor log functions

---

pkg/sriov-fec/clusterconfig.go
pkg/sriov-fec/clusterconfig_test.go
pkg/sriov-fec/clusterconfiglist.go
pkg/sriov-fec/clusterconfiglist_test.go
pkg/sriov-fec/const.go

Add `sriovfecclusterconfigs` CR of `sriovfec.intel.com/v2` API

sriov-fec: add clusterconfig CR

---

pkg/pod/pod.go
pkg/pod/pod_test.go

(cherry picked from commit f3976ee731b2484c2e935c733e34e49a58bdcb49)
(cherry picked from commit 0eaea1513f908d067fe196bc2476f01f2b8430d3)

Method ExecCommandWithTimeout added (#1143)
